### ISSUE TITLE
Bob+Angel - unable to recycle lowest-grade items (game version 0.17.50)

### ISSUE THREAD

**Issue by MikeRosoft** [DRY411S/Recycling-Machines#60] opened 2019-06-22 13:23 UTC
I have installed Bob's and Angel's mods. After building level 2 recycling machine, it appears that I can't recycle the lowest-grade items (I can't find the recycling recipes). Recycling low-grade items which can't be upgraded to higher grade is the whole point of this mod.

Items with missing recycling recipes:
* Pistol
* Light armor
* Burner inserter
* Inserter
* Burner mining drill
* Small electric pole
* Wooden chest
* Stone furnace

Game save: https://app.box.com/s/ow3vf3xuidg5ds5qgm7pmnvzloxnkvay

**Comment by DRY411S** [comment] 2019-06-22 14:01
This looks identical to Issue #49 and was fixed in v0.17.2 of the mod. Can you confirm that you have the latest version please.

**Comment by MikeRosoft** [comment] 2019-06-22 14:53
I have ZRecycling version 0.17.8.

**Comment by MikeRosoft** [comment] 2019-06-22 14:56
List of installed mods:

angelsaddons-cab_0.1.3.zip
angelsaddons-oresilos_0.5.1.zip
angelsaddons-petrotrain_0.4.0.zip
angelsaddons-pressuretanks_0.4.1.zip
angelsaddons-smeltingtrain_0.2.0.zip
angelsaddons-warehouses_0.4.1.zip
angelsbioprocessing_0.6.2.zip
angelsindustries_0.2.0.zip
angelsinfiniteores_0.8.9.zip
angelspetrochem_0.8.5.zip
angelspetrochem_0.8.6.zip
angelsrefining_0.10.13.zip
angelssmelting_0.5.7.zip
bobassembly_0.17.4.zip
bobelectronics_0.17.5.zip
bobenemies_0.17.7.zip
bobequipment_0.17.2.zip
bobgreenhouse_0.17.1.zip
bobinserters_0.17.5.zip
boblibrary_0.17.4.zip
boblogistics_0.17.11.zip
bobmining_0.17.3.zip
bobmodules_0.17.4.zip
bobores_0.17.4.zip
bobplates_0.17.9.zip
bobpower_0.17.7.zip
bobrevamp_0.17.4.zip
bobtech_0.17.3.zip
bobvehicleequipment_0.17.5.zip
bobwarfare_0.17.10.zip
Bottleneck_0.10.4.zip
clock_0.17.6.zip
FNEI_0.2.5.zip
helmod_0.8.11.zip [disabled]
rso-mod_5.0.9.zip
SpaceMod_0.4.4.zip
Squeak Through_1.3.0.zip
what-is-it-really-used-for_1.4.3.zip [disabled]
ZRecycling_0.17.8.zip

**Comment by MikeRosoft** [comment] 2019-06-22 14:58
In addition, when I start a new game, it appears that the recycling recipes don't exist either.

**Comment by DRY411S** [comment] 2019-06-22 15:08
I suspect the mods may be a red herring. I will first try to reproduce in vanilla.

**Comment by DRY411S** [comment] 2019-06-22 21:09
I cannot reproduce this is vanilla. There would appear to be a mod clash.

**Comment by DRY411S** [comment] 2019-06-22 21:52
@MikeRosoft that save game link appeas to be incorrect.

**Comment by DRY411S** [comment] 2019-06-22 21:53
In sandbox scenario mode, with all the mods loaded I cannot reproduce this error.

**Comment by MikeRosoft** [comment] 2019-06-23 19:10
I have corrected the URL of the game save.

**Comment by MikeRosoft** [comment] 2019-06-23 19:18
I have tested this in sandbox mode. Initially, the recycling recipe doesn't exist; but it appears when I unlock all technologies. (I have tested it by checking for the existence of recycling recipe for pistol.)

**Comment by DRY411S** [comment] 2019-06-29 10:32
I'm struggling to reproduce this issue.

When I start anew game, there are no recycling recipes. That's what I would expect because things can be recycled ONLY in Recycling Machines.

Recycling Machines are unlocked by researching Automation. As soon as this research is complete (both in vanilla and with all Bobs/Angels mods that you list), then the recycling recipes for base items are enabled, because the recycling machine is enabled.

**Comment by DRY411S** [comment] 2019-06-29 21:28
Maybe this is a workaround until I find out what is going wrong? https://mods.factorio.com/mod/First_phase_recycling

@MikeRosoft

**Comment by DRY411S** [comment] 2019-06-30 09:35
I cannot reproduce this issue, and all attempts to make the missing items appear in your save game have failed.

I've written bespoke migration scripts, I've removed and readded the mod, those recipes just seem to be disabled somehow.

Debug statements show that the recipes are there and enabled when the game starts up.

Then, after loading the saved game, the migration script again enables them.

I've written an event handler that fires every game tick. This shows that the recycling recipe for the pistol is disabled again.

Since I cannot reproduce this on any new games with all these mods, I'm going to assume that this has been caused by an older version of one of the other mods, so I cannot fix.

As part of the investigating of this issue, I've discovered some 'irrational' behaviour of the mod, and decided to change mod behaviour an raised issue #64 . Regrettably, it won't fix the problem in your save.

**Comment by DRY411S** [comment] 2019-06-30 09:54
I cannot fix this issue in your file, one of the other mods is disabling the recipes. I can show that I enable them before the savegame is loaded, but immediately afterwards, they are disabled again.
I cannot reproduce this issue with new games and those mods you listed.
The mod I listed above (after you have researched recycling) gets rid of the problem on your save game.

So I am going to flag this as 'wontfix' I'm afraid since it appears to be a one-off. In investigating the issue, I've decided to change the mod's behaviour at the start of a new game and raised #64 to fix this. The fix for that still does not solve your issue.

**Closed** 2019-07-08 04:13 UTC
Labels: Under Investigation, wontfix
