### ISSUE TITLE
updating the mod from 15 to 16 

### ISSUE THREAD

**Issue by dutchuss2016** [DRY411S/Recycling-Machines#42] opened 2017-12-23 12:26 UTC
updating the mod from 15 to 16 result in the lost ability to change the recipie of a placed recycler i have been using the mod to recycle belts on my map and all the other useless garbage that was flooding my storage and now i cant us them if i place a new recycler and click on it i get no interface to set the recipie with
![image](https://user-images.githubusercontent.com/32156904/34319529-0f0b5772-e7aa-11e7-83d4-179ca32c93f0.png )the image shows a recycler from v.15 that is still recycling the one below that i just placed and clicked on before i took the screen shot as you can see there is no interface to set the recipie

**Comment by DRY411S** [comment] 2017-12-23 12:48
Thank you for reporting this issue.

It is caused by me forgetting to provide a 'migrations' upgrade script. I will fix in the next release.

In the meantime, here is a workaround.

Toggle the mod off in your in game menu.
Load your saved game that has the problem. (All your recycling machines will be gone I think.)
Save the game (use a different name to be safe)
Get back to factorio main menu
Toggle the mod back on again
Load the saved game you created above

These steps should cause the recycling machines to have the correct recipes again.

**Comment by dutchuss2016** [comment] 2017-12-23 12:59
i will give this a try and see if it works im actively playing factorio right now

**Comment by dutchuss2016** [comment] 2017-12-23 13:07
![image](https://user-images.githubusercontent.com/32156904/34319787-e0e2512e-e7af-11e7-9601-8b019a9c73fe.png)

**Comment by dutchuss2016** [comment] 2017-12-23 13:08
since that work around worked is my old save borked and should i just move on without it (only lost like a few hundred steel and some batteries not that big a deal compared to the mega base i have

**Comment by DRY411S** [comment] 2017-12-23 14:55
@dutchuss2016  said
> since that work around worked is my old save borked and should i just move on without it (only lost like a few hundred steel and some batteries not that big a deal compared to the mega base i have

If you are confident to unzip the mod and make sure it gets placed in the factorio mod folder, you could try this, and use your old save where you first saw the problem.

- Where

 ZRecycling_0.16.1. zip is now (in the mods folder) unzip it so you have this path structure:![image](https://user-images.githubusercontent.com/19732374/34320372-c5a58cf0-e7f0-11e7-9515-0e39d9c136f4.png) (You won't have the .git folder or the file with 'no name'.

- In the migrations folder, rename ZRecycling_0.15.2.lua to ZRecycling_0.16.1.lua
- Start the game, make sure the mod is enabled, load your 0.15 saved game, and this time you should have the recycling recipes back

**Comment by DRY411S** [comment] 2017-12-27 13:06
Fixed in v0.16.2

**Closed by DRY411S** 2017-12-27 13:06 UTC
Labels: bug
