### ISSUE TITLE
__ZRecycling__/data-final-fixes.lua:262: bad argument #1 to 'pairs' (table expected, got nil)

### ISSUE THREAD

**Issue by mrbaguette** [DRY411S/Recycling-Machines#40] opened 2017-08-15 18:55 UTC
Updated to latest version and now the mod fails to load.

```
   9.318 Loading mod ZRecycling 0.15.5 (data-final-fixes.lua)
   9.324 Error ModManager.cpp:957: Failed to load mod "ZRecycling": __ZRecycling__/data-final-fixes.lua:262: bad argument #1 to 'pairs' (table expected, got nil)
   9.326 Loading mod core 0.0.0 (data.lua)
   9.386 Checksum for core: 2985821474
   9.527 Error ModManager.cpp:957: Error in assignID, resource-category with name 'basic-solid' does not exist.

Source: starting-area (noise-layer).
   9.651 Loaded shader file D:/games/steamapps/common/Factorio/data/core/graphics/shaders/game.cso
   9.651 Loaded shader file D:/games/steamapps/common/Factorio/data/core/graphics/shaders/zoom-to-world.cso
   9.657 Initial atlas bitmap size is 16384
   9.658 Created atlas bitmap 192x5
   9.658 Created atlas bitmap 132x24
   9.839 Sprites loaded
   9.839 Convert atlas 132x24 to: trilinear-filtering 
   9.842 Custom inputs active: 0
   9.853 Factorio initialised
   9.853 Mods to disable:Failed to load mods: __ZRecycling__/data-final-fixes.lua:262: bad argument #1 to 'pairs' (table expected, got nil)

Mods to be disabled:
• ZRecycling

```

**Comment by DRY411S** [comment] 2017-08-15 22:48
Thanks for the report.

Which version did you update from?

My mod expects that all recipes have ingredients AND something (a result) which is made from those ingredients.

Please say what mods you are using. You have a mod which has a recipe which has ingredients but no result.

**Comment by mrbaguette** [comment] 2017-08-18 15:35
Actually, I'm using the 0.15.5 since July 22nd. It means the error occurs since I have updated another mod.
It would be nice that ZRecycling tells which mod is the culprit though. I have a big list of mods and finding the bad one is a bit cumbersome.

Also, ZRecycling could ignore the faulty recipe and show a warning at the beginning of the game?

Mod list:

1. Additional-Turret 0.1.8
2. Additional-Turret 0.1.8
3. Bio_Industries 1.8.2
4. Bio_Industries 1.8.2
5. DeepMine 0.1.3
6. EndgameCombat 0.0.5
7. EvoGUI 0.4.207
8. FARL 1.1.7
9. Factorissimo2 2.1.8
10. Flare Stack 2.1.4
11. Flow Control 3.0.2
12. Geothermal 1.0.0
13. Honk 2.1.3
14. IncendiaryMunitions 0.3.0
15. KS_Power 0.1.12
16. Localized_Charging 1.1.0
17. MIRV 0.1.1
18. Nuclear Locomotives 1.1.2
19. Orbital Ion Cannon 1.5.2
20. PickerExtended 2.8.1
21. Rampant 0.15.21
22. SmartDisplayRedux 1.1.1
23. SmartTrains 2.1.0
24. Teleportation 0.15.7
25. TheFatController 2.0.11
26. TimeTools 1.0.29
27. TurretDelay 1.0.2
28. Turtle_Speed 0.2.2
29. aai-vehicles-chaingunner 0.2.4
30. aai-vehicles-chaingunner 0.2.4
31. aai-vehicles-flame-tumbler 0.2.3
32. aai-vehicles-laser-tank 0.2.1
33. advanced-logistics-system 0.5.1
34. alien-biomes 0.2.7
35. alien-space-science 0.0.4
36. angelsaddons-warehouses 0.2.1
37. angelsaddons-warehouses 0.2.1
38. angelsinfiniteores 0.6.11
39. base 0.15.33
40. base 0.15.33
41. bobassembly 0.15.7
42. bobenemies 0.15.2
43. boblibrary 0.15.8
44. boblogistics 0.15.6
45. bobmining 0.15.2
46. bobpower 0.15.4
47. bobvehicleequipment 0.15.2
48. cncs_Sulfur_Mod 1.0.2
49. core 0.0.0
50. creative-mode 0.3.10
51. data-raw-prototypes 0.3.1
52. folk-shuttle 0.1.12
53. helmod 0.5.7
54. recursive-blueprints 0.15.10
55. research-queue 1.5.1
56. robotMiningSite 0.6.2
57. rso-mod 3.3.11
58. supportive-weapons 0.3.1
59. upgrade-planner 1.4.10
60. water-fix 0.2.1

**Comment by DRY411S** [comment] 2017-08-19 07:08
> Actually, I'm using the 0.15.5 since July 22nd. It means the error occurs since I have updated another mod.

It's possible then that one of the other mods could have a bug.

> It would be nice that ZRecycling tells which mod is the culprit though. I have a big list of mods and finding the bad one is a bit cumbersome.

> Also, ZRecycling could ignore the faulty recipe and show a warning at the beginning of the game?

It would be nice, I will explore whether it is possible to output the bad recipe into the log file during this bug fix.

Essentially the bug fix will be to ignore the recipe. The recipe that causes this error has no results, therefore there is nothing to put into the Recycling Machine

> Mod list:

Wow! This may take some time to find and fix.

**Comment by DRY411S** [comment] 2017-08-20 06:46
Testing with:

Mod|Your Version|Test Version
---|---|---
Additional-Turret |0.1.8
Bio_Industries |1.8.2 |1.8.5
DeepMine |0.1.3
EndgameCombat |0.0.5|1.0.24
EvoGUI |0.4.207
FARL |1.1.7
Factorissimo2 |2.1.8
Flare Stack |2.1.4
Flow Control |3.0.2
Geothermal |1.0.0
Honk |2.1.3
IncendiaryMunitions |0.3.0
KS_Power |0.1.12
Localized_Charging |1.1.0
MIRV |0.1.1
Nuclear Locomotives |1.1.2
Orbital Ion Cannon |1.5.2
PickerExtended |2.8.1
Rampant |0.15.21
SmartDisplayRedux |1.1.1
SmartTrains |2.1.0
Teleportation |0.15.7
TheFatController |2.0.11
TimeTools |1.0.29
TurretDelay |1.0.2
Turtle_Speed |0.2.2
aai-vehicles-chaingunner |0.2.4
aai-vehicles-flame-tumbler |0.2.3
aai-vehicles-laser-tank |0.2.1
advanced-logistics-system |0.5.1
alien-biomes |0.2.7
alien-space-science |0.0.4|Not on portal
angelsaddons-warehouses |0.2.1|0.2.2
angelsinfiniteores |0.6.11
base |0.15.33
bobassembly |0.15.7
bobenemies |0.15.2
boblibrary |0.15.8
boblogistics |0.15.6
bobmining |0.15.2
bobpower |0.15.4
bobvehicleequipment |0.15.2
cncs_Sulfur_Mod |1.0.2
core |0.0.0
creative-mode |0.3.10
data-raw-prototypes |0.3.1
folk-shuttle |0.1.12
helmod |0.5.7
recursive-blueprints |0.15.10
research-queue |1.5.1
robotMiningSite |0.6.2
rso-mod |3.3.11|3.3.12
supportive-weapons |0.3.1
upgrade-planner |1.4.10
water-fix |0.2.1

**Comment by DRY411S** [comment] 2017-08-20 07:47
The problem is caused by the Supportive Weapons mod, which has a recipe with no results. This really doesn't make any sense.

`{
  allow_decomposition = false,
  category = "advanced-crafting",
  enabled = false,
  energy_required = 10,
  icon = "__supportive-weapons__/graphics/icons/tissue-leaching.png",
  ingredients = {
    {
      amount = 1,
      name = "supportive-weapons_dissolved-tissue",
      type = "item"
    },
    {
      amount = 5,
      name = "sulfuric-acid",
      type = "fluid"
    }
  },
  main_product = "",
  name = "supportive-weapons_tissue-leaching",
  order = "i[supportive-weapons]-a[tissue-leaching]",
  requester_paste_multiplier = 10,
  subgroup = "raw-material",
  type = "recipe"
}
`

**Comment by DRY411S** [comment] 2017-08-23 06:36
A fix for this is in development for the next release, which will also include some new features and performance improvements.

**Closed** 2017-08-24 18:11 UTC
Labels: bug
