### ISSUE TITLE
Error Loading Mod

### ISSUE THREAD

**Issue by Rhayvin** [DRY411S/Recycling-Machines#30] opened 2017-05-01 18:10 UTC
Upon startup getting the following message

Failed to load mods:__ZRecycling__/data-final-fixes.lua:247:bad argument #1 to 'pairs' (table expected got nil)

**Comment by DRY411S** [comment] 2017-05-02 02:59
This does not happen with vanilla factorio (0.15.3), and therefore must be caused by a mod that you are using.

Please confirm the mods (and versions) that you are using, and I will investigate further. Even better, please disable all your mods, renable this one, and then add mods back in one at a time, to see which one it is that is causing this error.

**Comment by canadajebus** [comment] 2017-05-02 20:04
I'm getting this as well.  I'm using all the bobs and angels mods that have been updated so far.

**Comment by DRY411S** [comment] 2017-05-02 21:04
Please could you paste the contents of your mod-list.json file from your factorio mods folder so that I can see exactly what mods you have active.

This is typically in the folder C:\Users\<yourusername>\AppData\Roaming\Factorio\mods if you're usung the STEAM version of factorio.

You can open mod-list.json with any text editor.

**Comment by canadajebus** [comment] 2017-05-02 21:07
{
  "mods": [
    {
      "name": "base",
      "enabled": true
    },
    {
      "name": "TheFatController",
      "enabled": true
    },
    {
      "name": "what-is-it-used-for",
      "enabled": true
    },
    {
      "name": "angelsaddons-petrotrain",
      "enabled": true
    },
    {
      "name": "bobconfig",
      "enabled": true
    },
    {
      "name": "bobenemies",
      "enabled": true
    },
    {
      "name": "bobinserters",
      "enabled": true
    },
    {
      "name": "boblibrary",
      "enabled": true
    },
    {
      "name": "Bottleneck",
      "enabled": true
    },
    {
      "name": "EvoGUI",
      "enabled": true
    },
    {
      "name": "jvmguy-no-hand-crafting",
      "enabled": true
    },
    {
      "name": "no-hand-crafting",
      "enabled": true
    },
    {
      "name": "ZRecycling",
      "enabled": false
    },
    {
      "name": "bobores",
      "enabled": true
    },
    {
      "name": "bobtech",
      "enabled": true
    },
    {
      "name": "bobvehicleequipment",
      "enabled": true
    },
    {
      "name": "RecycleRatio050",
      "enabled": true
    },
    {
      "name": "bobplates",
      "enabled": true
    },
    {
      "name": "rso-mod",
      "enabled": true
    },
    {
      "name": "angelsrefining",
      "enabled": true
    },
    {
      "name": "bobassembly",
      "enabled": true
    },
    {
      "name": "bobelectronics",
      "enabled": true
    },
    {
      "name": "bobgreenhouse",
      "enabled": true
    },
    {
      "name": "boblogistics",
      "enabled": true
    },
    {
      "name": "bobmining",
      "enabled": true
    },
    {
      "name": "bobpower",
      "enabled": true
    },
    {
      "name": "bobrevamp",
      "enabled": true
    },
    {
      "name": "angelsaddons-oresilos",
      "enabled": true
    },
    {
      "name": "angelsaddons-warehouses",
      "enabled": true
    },
    {
      "name": "angelspetrochem",
      "enabled": true
    },
    {
      "name": "bobmodules",
      "enabled": true
    },
    {
      "name": "bobwarfare",
      "enabled": true
    },
    {
      "name": "ScienceCostTweaker",
      "enabled": true
    },
    {
      "name": "angelsaddons-pressuretanks",
      "enabled": true
    },
    {
      "name": "angelsbioprocessing",
      "enabled": true
    },
    {
      "name": "angelsinfiniteores",
      "enabled": true
    },
    {
      "name": "angelssmelting",
      "enabled": true
    },
    {
      "name": "marathomaton",
      "enabled": false
    }
  ]
}

**Comment by canadajebus** [comment] 2017-05-02 21:08
Some of those say enabled, but they are not because they are not 0.15.

**Comment by DRY411S** [comment] 2017-05-02 21:11
Great thanks, I'll download these and take a look to see which mod is causing the error message, and why.

**Comment by DRY411S** [comment] 2017-05-03 09:39
@Rhayvin please can you confirm whether you are using Bob's Greenhouse mod.

@canadajebus from that list above, the only mod that is causing this error is Bob's Greenhouse.

Accepted as bug.

**Comment by DRY411S** [comment] 2017-05-03 10:08
Fixed in v0.15.2 https://github.com/DRY411S/Recycling-Machines/commit/6099ff0ff523af424817eaf83c1fc1cc1beb64df

**Closed by DRY411S** 2017-05-03 10:08 UTC
Labels: bug, Under Investigation
